#
# .travis.yml
#

language: "node_js"

node_js:
  - "stable"
  # Long-term Support
  - "4.2" # Argon

install:
  # Install Global Modules
  - "npm install eslint@^1.0.0 babel-eslint ubfg/eslint-config-ubf"
  - "npm install mocha"

  # Install Local Modules
  - "npm install"

  # Install Test Modules
  - "npm --prefix test install"

script:
  # ESLint
  - "node_modules/.bin/eslint src"

  # Mocha
  - "node_modules/.bin/mocha test"
